### GET request with a header
GET http://localhost:3000/api/products/1
Accept: application/json

### GET request with a header
GET http://localhost:3000/api/products
Accept: application/json

### GET request with parameter
GET http://localhost:3000/api/products?limit=2&offset=2&withTags=true&withCategories=true
Accept: application/json

### GET request with parameter and tag
GET http://localhost:3000/api/products?tag=P&limit=2&offset=0
Accept: application/json

### Send POST request with json body
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Rasberry Pi 4B",
  "author": "m.czaniecki@gmail.pl",
  "code": "202z3AJ10491",
  "description": "Rasberry Pi 4B 4GB RAM"
}

### Send PUT request with json body
PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
  "name": "Rasberry Pi 4G",
  "description": "Rasberry Pi 4B 4GB RAM",
  "tag_id": 1
}

### DELETE request with a header
DELETE http://localhost:3000/api/products/1
Accept: application/json
